### ISSUE TITLE
Service registry link server down - 503 unavailable

### ISSUE THREAD

**Issue by davmlaw** [ga4gh-beacon/ga4gh-beacon.github.io#1]
https://genomebeacons.org/

Has a link to Beacon [Service Registry](https://ga4gh-approval-service-registry-demo.ega-archive.org/)

https://ga4gh-approval-service-registry-demo.ega-archive.org/ gives a 503 Service Unavailable

Q) Is this supposed to have demo in the name?

**Comment by mbaudis** [comment]
@davmlaw Thanks for pointing this out. This wasn't a proper registry but a prototype version maintained by CRG/EGA for the 4 Beacons used during v2 approval process (including ours at [progenetix.org](https://progenetix.org); doc page [here](https://docs.progenetix.org/common/beacon-api/)). 

For now I have removed the broken EGA links and hopefully we'll add a proper registry at some point ...

**Comment by davmlaw** [comment]
Maybe I don't understand it fully but doesn't it rely on a registry for people to know about it?

Why would anyone implement an API on their genomics server if nobody's going to use it?

**Comment by davmlaw** [comment]
Even a flat text file of URLs on github would do.

Get that then loop through them

**Comment by mbaudis** [comment]
@davmlaw 

> Even a flat text file of URLs on github would do.

Exactly. Do you want to work on one? I'm happy to help!

The problem is that it is not necessarily part of the developers' work to develop and maintain such a registry; it is a public standard w/ many implementations and it is out of our hand... There are lists and network implementations

* Beacon network: A somehow coordinated set of beacons with one or more aggregators
* Beacon aggregator: Uses a list of beacon endpoints for sending queries and aggregating results, usually with a web front end

... such as the ELIXIR Beacon network but a lot of these include "we're in a development stage" etc. and are focused on what they're doing.

Here is a list of 3 beacons:

* [progenetix](https://progenetix.org/beacon/)
* [cancercelllines.org](https://cancercelllines.org/beacon/)
* [RefCNV](https://refcnv.org/beacon/)

... and here is a list somebody at CRG started etc.:

https://docs.google.com/spreadsheets/d/1TetikAVPk_-UR6IShYCKA5PGJbR4Us_kCru3GCdnL6k/edit?gid=0#gid=0

... and as map https://public.tableau.com/app/profile/elixir/viz/ELIXIRBeaconNetwork/Sheet1

We  just need a project, with responsibilities and such, to build a sustainable registry.

**Comment by davmlaw** [comment]
Thanks for the link to the Google doc.

I understand about resources. It's possible I may contribute in the future but I'd want to implement beacon as both a server and client first. After that I'll get my sites added to the Google doc, then see what the state of things is.
